#!/usr/bin/sh

# Redirect output to stderr.
exec 1>&2

## Cargo spell-check
#
# Cargo spellcheck can be configured with -m <code> to return a non-zero
# return code if mistakes are found instead of 0.
#
exec cargo spellcheck -m 99 $(git diff-index --cached --name-only --diff-filter=AM HEAD)