[book]
title = "The Goose Book"
authors = [""]
description = "Load testing framework, inspired by Locust, implemented with Rust."
language = "en"

[rust]
edition = "2018"

[build]
build-dir = "html"
create-missing = true

[output.html]
mathjax-support = true